# Generated by Django 5.0 on 2024-09-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('senha', models.TextField()),
                ('telefone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('localizacao', models.TextField()),
                ('descricao', models.CharField(max_length=180)),
                ('foto', models.TextField()),
                ('conta_bancaria', models.TextField()),
                ('chave_pix', models.TextField()),
                ('tipo_usuario', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
            ],
        ),
    ]
