# Generated by Django 5.0 on 2024-09-08 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('raca', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
                ('tamanho', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=1)),
                ('localizacao', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=80)),
                ('foto', models.TextField()),
                ('data_criacao', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('data_adocao', models.DateField()),
                ('id_adotador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adotador', to='api.usuario')),
                ('id_doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doador', to='api.usuario')),
            ],
        ),
    ]
