# Generated by Django 5.0 on 2024-09-19 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_usuario_senha_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id_adotador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adotador', to=settings.AUTH_USER_MODEL),
        ),
    ]
