# Generated by Django 5.0 on 2024-09-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_animal_id_adotador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='data_adocao',
            field=models.DateField(null=True),
        ),
    ]
