# Generated by Django 5.0 on 2024-09-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_animal_data_adocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id_animal',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
