# Generated by Django 5.0 on 2024-09-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_animal_id_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id_adotador',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id_doador',
            field=models.TextField(),
        ),
    ]
