# Generated by Django 5.0 on 2024-09-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_animal_id_adotador_alter_animal_id_doador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='data_criacao',
            field=models.DateField(null=True),
        ),
    ]
