# Generated by Django 5.0 on 2024-09-19 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_animal_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id_adotador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adotador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id_animal',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id_doador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doador', to=settings.AUTH_USER_MODEL),
        ),
    ]
