# Generated by Django 5.0 on 2024-09-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_animal_id_adotador_alter_animal_id_animal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='nome',
            new_name='animal_nome',
        ),
    ]
